# Processando os arquivos de logs para gerar o data drift

In [3]:
import pandas as pd
import os
import json

In [4]:
directory_path = "./docker/log/"

In [5]:
def process_logs(directory_path, included_extensions=['.log']):
    files = [f for f in os.listdir(directory_path) if os.path.isfile(os.path.join(directory_path, f)) and os.path.splitext(f)[1] in included_extensions]

    print(f"{len(files)} arquivos encontrados para o processamento")

    df_default_propensity_inputs = pd.DataFrame()
    df_customer_clustering_inputs = pd.DataFrame()
    df_default_propensity_outputs = pd.DataFrame()
    df_customer_clustering_outputs = pd.DataFrame()

    for filename in files:
        filepath = os.path.join(directory_path, filename)

        with open(filepath, 'r') as file:
            data = json.load(file)

        if data['model'] == 'customer_clustering':
            df_customer_clustering_inputs = pd.concat([df_customer_clustering_inputs, pd.DataFrame(data['input']['content'], index=[0])])
            df_customer_clustering_outputs = pd.concat([df_customer_clustering_outputs, pd.DataFrame(data['output']['content'], index=[0])])
        elif data['model'] == 'default_propensity':
            df_default_propensity_inputs = pd.concat([df_default_propensity_inputs, pd.DataFrame(data['input']['content'], index=[0])])
            df_default_propensity_outputs = pd.concat([df_default_propensity_outputs, pd.DataFrame(data['output']['content'], index=[0])])

    return df_default_propensity_inputs, \
        df_customer_clustering_inputs, \
        df_default_propensity_outputs, \
        df_customer_clustering_outputs

In [6]:
df_dp_in, df_cc_in, df_dp_out, df_cc_out = process_logs(directory_path)

10 arquivos encontrados para o processamento

In [14]:
df_cc_in

,loan_purpose,Security_Type,age,Region,year,loan_amount,term,property_value,income,Credit_Score,LTV,dtir1
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,790,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,400,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,796,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,796,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,100,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,180.0,790,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,796,48.046875,18.0
0,p4,direct,45-54,North,2019,676500,360.0,1408000.0,19380.0,100,48.046875,18.0